### PR TITLE
Improve Model calculations and thread-safety

### PR DESCRIPTION
**Pull request by DarthSharkie**
Clean up model, add builder, improve parser so it's thread-safe and produces read-only object models.

Tested with the ender dragon model scaled and rotating.

### CODE REVIEW

**Comment by DarthSharkie** [comment]
OK, fixed to allow for N vertices per face.

**Comment by GitBrincie212** [comment]
There is a conflict with the particle object

**Comment by DarthSharkie** [comment]
OK, will look/resolve.

**Comment by GitBrincie212** [comment]
Triple The Conflicts!

**Comment by DarthSharkie** [comment]
OK, rebased this again.  It should be conflict-free, unless there are more changes I haven't pulled down.  This takes your recent changes and adds in the ObjParser work I did to try to tie it all together.

**Pull request merged**
